-------------------------
-- CLIENT TABLE
-------------------------
CREATE SEQUENCE IF NOT EXISTS client_id_seq;
CREATE table IF NOT EXISTS client (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL
);

-------------------------
-- ROLE TABLE
-------------------------

CREATE SEQUENCE IF NOT EXISTS role_id_seq;
CREATE TABLE IF NOT EXISTS role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR,
    role_value VARCHAR NOT NULL,
	 FOREIGN KEY (client_id) REFERENCES client(client_id) ON DELETE CASCADE
);

-------------------------
-- CLAIM TABLE
-------------------------
CREATE SEQUENCE IF NOT EXISTS claim_id_seq;
CREATE TABLE IF NOT EXISTS claim (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     client_id VARCHAR,
	 scope VARCHAR,
     claim_name VARCHAR,
     expiration_time BIGINT,
	 FOREIGN KEY (client_id) REFERENCES client(client_id) ON DELETE CASCADE
     
);
